image:
  repository: gcr.io/google_containers/echoserver
  tag: '1.10'

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: enabled
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts: []
    # - chart-example.local
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
